version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - $HOME/data:/data
    environment:
      MINIO_ACCESS_KEY: digitalse
      MINIO_SECRET_KEY: digitalse
    command: server /data
    networks:
      - digitalse-network
  postgres:
    image: postgres:15.5-alpine3.19
    container_name: digitalse-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digitalsedb
    ports:
      - "5434:5432"
    volumes:
      - $HOME/.postgres/digitalsedb/data/postgresql:/var/lib/postgresql/data
    networks:
      - digitalse-network
  digitalseapi:
    build:
      context: ./digitalseapi
      dockerfile: Dockerfile
    image: digitalseapi
    ports:
      - "8000:8000"
    volumes:
      - $HOME/data:/home/app/images
    depends_on:
      - minio
      - postgres
    networks:
      - digitalse-network
networks:
  digitalse-network:
volumes:
  postgres_data:
  minio_data:
  local-images:
