version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - $HOME/data:/data
    environment:
      MINIO_ACCESS_KEY: digitalse
      MINIO_SECRET_KEY: digitalse
    command: server /data
    networks:
      - digitalse-network
  postgres:
    image: postgres:15.5-alpine3.19
    container_name: digitalse-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digitalsedb
    ports:
      - "5434:5432"
    volumes:
      - $HOME/.postgres/digitalsedb/data/postgresql:/var/lib/postgresql/data
    networks:
      - digitalse-network
  digitalseapi:
    build:
      context: ./digitalseapi
      dockerfile: Dockerfile
    image: digitalseapi
    ports:
      - "8000:8000"
    volumes:
      - $HOME/data:/home/app/images
    env_file:
      - ./digitalseapi/.env
    depends_on:
      - minio
      - postgres
      - rabbitmq
    networks:
      - digitalse-network
  rabbitmq:
    image: rabbitmq:3.12.13-management
    ports:
      - "5672:5672" # Porta para conexões AMQP
      - "15672:15672" # Porta para o painel de controle do RabbitMQ (opcional)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - digitalse-network
  ocrservice:
    build: 
      context: ./ocrservice
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - digitalse-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - digitalse-network  

networks:
  digitalse-network:

volumes:
  data_postgres:
  minio_data:
  local-images:
  rabbitmq_data:
  mongo_data:
